name: CI

on: [pull_request]

jobs:
  build:
    runs-on: macOS-latest
    env:
      XCODE_VERSION: ${{ '13.1' }}
    steps:
      - name: Select Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ./build.sh
