name: CI

on: [pull_request]

jobs:
  build:
    runs-on: macOS-12
    env:
      XCODE_VERSION: ${{ '14.0' }}
    steps:
      - name: Select Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: ./build.sh
